apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created 
  #in the Kubernetes cluster
  name: flask-app-service 
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000 #Service port
    targetPort: 8000 #The port for the application container